### ISSUE TITLE
Cannnot initialize CoinbaseSDK in Nuxt3 project

### ISSUE THREAD

**Issue by thehedgeguy** [coinbase/coinbase-wallet-sdk#424]
`new CoinbaseWalletSDK()` is throwing this error on a Nuxt3 project

```
stream_readable.js:48 Uncaught ReferenceError: global is not defined
    at node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:48:21)
    at __require (chunk-36VY3QWH.js?v=4a71101f:25:50)
    at node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require (chunk-36VY3QWH.js?v=4a71101f:25:50)
    at node_modules/keccak/lib/api/keccak.js (keccak.js:1:23)
    at __require (chunk-36VY3QWH.js?v=4a71101f:25:50)
    at node_modules/keccak/lib/api/index.js (index.js:1:22)
    at __require (chunk-36VY3QWH.js?v=4a71101f:25:50)
    at node_modules/keccak/js.js (js.js:1:18)
    at __require (chunk-36VY3QWH.js?v=4a71101f:25:50)
```

importing it in `nuxt.config.ts` as a module throws
```
Cannot start nuxt:  Class constructor CoinbaseWalletSDK cannot be invoked without 'new'
```
```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/@coinbase/wallet-sdk/dist/index.js?v=50e0e371' does not provide an export named 'default'
```

**Comment by ljharb** [comment]
`global` works in node, and a working node module bundler automatically provides that as a pointer to window. If next doesn’t support that, please file a bug on it to do so. In the meantime, you can probably configure nuxt to provide it manually.
